### ISSUE TITLE
Final integration and testing

### ISSUE THREAD

**Issue by Amey2904dash** [cu-ecen-aeld/final-project-Amey2904dash#12]
DoD : 
- [x] Final project integration of all the sensors , execute and test the entire system on a multithreaded application.

Tasks :
- [x] Integrate all the sensors on the server application
- [x] Integrate all the sensors on the client application
- [x] Test the entire system

Blocker :
- [x] Working application code for facial recognition system on Buildroot. 
https://github.com/cu-ecen-aeld/final-project-Amey2904dash/issues/8
Resolved: [Link](https://github.com/cu-ecen-aeld/final-project-Amey2904dash/issues/8#issuecomment-1106215124)

**Comment by tanmay-mk** [comment]
Changed the facial recognition application so that instead of printing the person's name on terminal, it stores the name as a string in a text file 'names.txt' that is created using a startup script dynamically during boot-up time. 
Startup script : [Link](https://github.com/cu-ecen-aeld/final-project-varun2506/blob/main/base_external/rootfs_overlay/etc/init.d/S99initmodules), Check [this](https://github.com/cu-ecen-aeld/final-project-varun2506/blob/fdf971b5ef6354df6651257c53abc2865cce51c2/base_external/rootfs_overlay/etc/init.d/S99initmodules#L14) & [this](https://github.com/cu-ecen-aeld/final-project-varun2506/blob/fdf971b5ef6354df6651257c53abc2865cce51c2/base_external/rootfs_overlay/etc/init.d/S99initmodules#L15).

Changing the permission of these files. [Link](https://github.com/cu-ecen-aeld/final-project-varun2506/blob/fdf971b5ef6354df6651257c53abc2865cce51c2/base_external/rootfs_overlay/etc/init.d/S99initmodules#L16)

**Comment by tanmay-mk** [comment]
Even if the same person comes in front of the camera multiple times, their name will only be stored in the file once to avoid repetition. If the camera recognizes the same person again, it will print "<name of person> is already present" on the screen. 
 
![WhatsApp Image 2022-04-26 at 11 17 26 PM](https://user-images.githubusercontent.com/89433097/165447145-0f355c8c-486c-4a64-9c6f-43f29bdb296f.jpeg)

**Comment by tanmay-mk** [comment]
Latest code for facial recognition is [here](https://github.com/cu-ecen-aeld/final-project-tanmay-mk). 
Commit number: 128d63865b601ff3e8e76dd2ce60a368b7a2e51b

**Comment by Amey2904dash** [comment]
Tanmay's' Part of Final Integration & Testing is [here](https://github.com/cu-ecen-aeld/final-project-Amey2904dash/issues/13)
Varun's Part of Final Integration & Testing is [here](https://github.com/cu-ecen-aeld/final-project-Amey2904dash/issues/14)
Amey's Part of Final Integration & Testing is [here](https://github.com/cu-ecen-aeld/final-project-Amey2904dash/issues/15)
